stages:
  - build
  - deploy

build:
  stage: build
  script:
  - nice cmake -Bdoc_build -DTATOOINE_BUILD_DOC=1 -DTATOOINE_DOC_ONLY=1
  - nice cmake --build doc_build -- doc
  artifacts:
    expire_in: 4 hours
    paths:
      - doc_build/
  only:
  - main
  tags:
  except:
  - tags

deploy:
  stage: deploy
  script:
    - mkdir -p ~/pages.vc/tatooine
    - nice cp -r doc_build/doc/html/* ~/pages.vc/tatooine/
  only:
    - main
