stages:
  - build
  - deploy

build:
  stage: build
  script:
  - cmake -Bdoc_build -DTATOOINE_BUILD_DOC=1 -DTATOOINE_DOC_ONLY=1
  - cmake --build doc_build -- doc
  artifacts:
    paths:
      - doc_build/
  only:
  - master
  tags:
  except:
  - tags

deploy:
  stage: deploy
  script:
    - mkdir -p ~/pages.vc/tatooine
    - cp -r doc_build/doc/html/* ~/pages.vc/tatooine/
  only:
    - master

