#version 450
//==============================================================================
layout(local_size_x = 32, local_size_y = 32) in;
layout(binding = 0, r32f) uniform image2D data_tex;
//==============================================================================
const uvec2 res  = uvec2(imageSize(data_tex));
const uint  size = res.x * res.y;
//==============================================================================
void main() {
  const uvec2 idx2 = uvec2(gl_GlobalInvocationID.xy);
  if (idx2.x >= res.x || idx2.y >= res.y) { return; }
}
