\newcommand{\myBoldNotation}[1]{{\mathbf{#1}}}
\newcommand{\mySetNotation}[1]{{\mathbb{#1}}}
\newcommand{\RRSet}{{\mySetNotation{R}}}
\newcommand{\EESet}{{\mySetNotation{E}}}
\newcommand{\NNSet}{{\mySetNotation{N}}}
\newcommand{\QQSet}{{\mySetNotation{Q}}}
\newcommand{\CCSet}{{\mySetNotation{C}}}
\newcommand{\va}{{\myBoldNotation{a}}}
\newcommand{\vb}{{\myBoldNotation{b}}}
\newcommand{\vc}{{\myBoldNotation{c}}}
\newcommand{\vd}{{\myBoldNotation{d}}}
\newcommand{\ve}{{\myBoldNotation{e}}}
\newcommand{\vf}{{\myBoldNotation{f}}}
\newcommand{\vg}{{\myBoldNotation{g}}}
\newcommand{\vh}{{\myBoldNotation{h}}}
\newcommand{\vi}{{\myBoldNotation{i}}}
\newcommand{\vj}{{\myBoldNotation{j}}}
\newcommand{\vk}{{\myBoldNotation{k}}}
\newcommand{\vl}{{\myBoldNotation{l}}}
\newcommand{\vm}{{\myBoldNotation{m}}}
\newcommand{\vn}{{\myBoldNotation{n}}}
\newcommand{\nn}{{\myBoldNotation{n}}}
\newcommand{\vo}{{\myBoldNotation{o}}}
\newcommand{\vp}{{\myBoldNotation{p}}}
\newcommand{\pp}{{\myBoldNotation{p}}}
\newcommand{\vq}{{\myBoldNotation{q}}}
\newcommand{\vr}{{\myBoldNotation{r}}}
\newcommand{\rr}{{\myBoldNotation{r}}}
\newcommand{\vs}{{\myBoldNotation{s}}}
\newcommand{\vt}{{\myBoldNotation{t}}}
\newcommand{\vu}{{\myBoldNotation{u}}}
\newcommand{\vv}{{\myBoldNotation{v}}}
\newcommand{\vw}{{\myBoldNotation{w}}}
\newcommand{\ww}{{\myBoldNotation{w}}}
\newcommand{\vx}{{\myBoldNotation{x}}}
\newcommand{\xx}{{\myBoldNotation{x}}}
\newcommand{\vy}{{\myBoldNotation{y}}}
\newcommand{\vz}{{\myBoldNotation{z}}}
\newcommand{\vNull}{{\myBoldNotation{0}}}
\newcommand{\vOne}{{\myBoldNotation{1}}}
\newcommand{\mA}{{\myBoldNotation{A}}}
\newcommand{\mB}{{\myBoldNotation{B}}}
\newcommand{\mC}{{\myBoldNotation{C}}}
\newcommand{\mD}{{\myBoldNotation{D}}}
\newcommand{\mE}{{\myBoldNotation{E}}}
\newcommand{\mF}{{\myBoldNotation{F}}}
\newcommand{\mG}{{\myBoldNotation{G}}}
\newcommand{\mH}{{\myBoldNotation{H}}}
\newcommand{\mI}{{\myBoldNotation{I}}}
\newcommand{\mJ}{{\myBoldNotation{J}}}
\newcommand{\mK}{{\myBoldNotation{K}}}
\newcommand{\mL}{{\myBoldNotation{L}}}
\newcommand{\mM}{{\myBoldNotation{M}}}
\newcommand{\mN}{{\myBoldNotation{N}}}
\newcommand{\mO}{{\myBoldNotation{O}}}
\newcommand{\mP}{{\myBoldNotation{P}}}
\newcommand{\mQ}{{\myBoldNotation{Q}}}
\newcommand{\mR}{{\myBoldNotation{R}}}
\newcommand{\mS}{{\myBoldNotation{S}}}
\newcommand{\mT}{{\myBoldNotation{T}}}
\newcommand{\mU}{{\myBoldNotation{U}}}
\newcommand{\mV}{{\myBoldNotation{V}}}
\newcommand{\mW}{{\myBoldNotation{W}}}
\newcommand{\mX}{{\myBoldNotation{X}}}
\newcommand{\mY}{{\myBoldNotation{Y}}}
\newcommand{\mZ}{{\myBoldNotation{Z}}}
\newcommand{\mNull}{{\myBoldNotation{0}}}
\newcommand{\mOne}{\vOne\hspace{-.28em}\vOne}
\newcommand{\cA}{{\mathcal{A}}}
\newcommand{\cB}{{\mathcal{B}}}
\newcommand{\cC}{{\mathcal{C}}}
\newcommand{\cD}{{\mathcal{D}}}
\newcommand{\cE}{{\mathcal{E}}}
\newcommand{\cF}{{\mathcal{F}}}
\newcommand{\cG}{{\mathcal{G}}}
\newcommand{\cH}{{\mathcal{H}}}
\newcommand{\cI}{{\mathcal{I}}}
\newcommand{\cJ}{{\mathcal{J}}}
\newcommand{\cK}{{\mathcal{K}}}
\newcommand{\cL}{{\mathcal{L}}}
\newcommand{\cM}{{\mathcal{M}}}
\newcommand{\cN}{{\mathcal{N}}}
\newcommand{\cO}{{\mathcal{O}}}
\newcommand{\cP}{{\mathcal{P}}}
\newcommand{\cQ}{{\mathcal{Q}}}
\newcommand{\cR}{{\mathcal{R}}}
\newcommand{\cS}{{\mathcal{S}}}
\newcommand{\cT}{{\mathcal{T}}}
\newcommand{\cU}{{\mathcal{U}}}
\newcommand{\cV}{{\mathcal{V}}}
\newcommand{\cW}{{\mathcal{W}}}
\newcommand{\cX}{{\mathcal{X}}}
\newcommand{\cY}{{\mathcal{Y}}}
\newcommand{\cZ}{{\mathcal{Z}}}
\newcommand{\ca}{{\mathcal{a}}}
\newcommand{\cb}{{\mathcal{b}}}
\newcommand{\cc}{{\mathcal{c}}}
\newcommand{\cd}{{\mathcal{d}}}
\newcommand{\ce}{{\mathcal{e}}}
\newcommand{\cg}{{\mathcal{g}}}
\newcommand{\ch}{{\mathcal{h}}}
\newcommand{\ci}{{\mathcal{i}}}
\newcommand{\cj}{{\mathcal{j}}}
\newcommand{\ck}{{\mathcal{k}}}
\newcommand{\cl}{{\mathcal{l}}}
\newcommand{\cm}{{\mathcal{m}}}
\newcommand{\cn}{{\mathcal{n}}}
\newcommand{\co}{{\mathcal{o}}}
\newcommand{\cp}{{\mathcal{p}}}
\newcommand{\cq}{{\mathcal{q}}}
\newcommand{\cs}{{\mathcal{s}}}
\newcommand{\ct}{{\mathcal{t}}}
\newcommand{\cu}{{\mathcal{u}}}
\newcommand{\cv}{{\mathcal{v}}}
\newcommand{\cw}{{\mathcal{w}}}
\newcommand{\cx}{{\mathcal{x}}}
\newcommand{\cy}{{\mathcal{y}}}
\newcommand{\cz}{{\mathcal{z}}}
\renewcommand{\Transpose}[1]{{#1}^\Transp }
\newcommand{\TransposeInv}[1]{{#1}^{-\Transp} }
\newcommand{\T}[1]{\Transpose{#1}}
\newcommand{\TInv}[1]{\TransposeInv{#1}}
\newcommand{\Inv}[1]{{#1}^{-1} }
\newcommand{\Transp}{{{\mathrm T}}}
\newcommand{\Mcol}[2]{{#1}_{\cdot{}{#2}}}
\newcommand{\Rank}[1]{\operatorname{rank}\inp{#1}}
\newcommand{\Vol}[1]{\operatorname{vol}\inp{#1}}
\renewcommand{\Vec}[1]{\operatorname{vec}\inp{#1}}
\renewcommand{\Div}[1]{\T{\nabla} \, #1}
\newcommand{\Diag}[1]{\operatorname{diag}\inp{#1}}
\newcommand{\Dim}[1]{\operatorname{dim}\inp{#1}}
\newcommand{\Diagof}[1]{\operatorname{diag}^{-1}\inp{#1}}
\newcommand{\Argmin}[1]{\underset{#1}{\operatorname{argmin}} \;}
\newcommand{\Maxof}[1]{\underset{#1}{\operatorname{max}} \;}
\newcommand{\Minof}[1]{\underset{#1}{\operatorname{min}} \;}
\newcommand{\conj}[1]{{\overline{#1}}}
\newcommand{\CB}[1]{{\color{#1}$\bullet$}}
\newcommand{\CBB}[2]{{\color[#1]{#2}$\bullet$}}
\newcommand{\ie}{i.e.}
\newcommand{\Ie}{I.e.}
\newcommand{\eg}{e.g.}
\newcommand{\Eg}{E.g.}
\newcommand{\cf}{cf.\ }
\newcommand{\Cf}{Cf.\ }
\newcommand{\etc}{etc.\ }
\newcommand{\wrt}{w.r.t.\ }
\newcommand{\Wrt}{W.r.t.\ }
\newcommand{\Wlog}{W.l.o.g.\ }
\newcommand{\resp}{resp.\ }
\newcommand{\etal}{et al.\ }
