#version 450
//==============================================================================
#include "dual_binding.glsl"
//==============================================================================
uniform float min_btau;
uniform float max_ftau;
//==============================================================================
layout (local_size_x = 32, local_size_y = 32) in;
void main() {
  const ivec2 texpos = ivec2(gl_GlobalInvocationID.xy);
  if (texpos.x >= texres.x || texpos.y >= texres.y) { return; }

  const uint s0 =   imageLoad(list_size0, texpos).x;
  const uint s1 =   imageLoad(list_size1, texpos).x;
  imageStore(list_size0, texpos, uvec4(s0 + s1, 0, 0, 0));
}
