#version 450
//==============================================================================
layout(binding = 0, r32ui) uniform uimage2D    coverage_tex;
layout(binding = 0)        uniform atomic_uint covered_pixels;
//==============================================================================
const ivec2 resolution = imageSize(coverage_tex);
//==============================================================================
layout (local_size_x = 32, local_size_y = 32) in;
void main() {
  const ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
  if (pos.x <= 0 ||
      pos.y <= 0 ||
      pos.x >= resolution.x ||
      pos.y >= resolution.y) { return; }

  uint covered = imageLoad(coverage_tex, pos).r;
  if (covered != 0) { atomicCounterIncrement(covered_pixels); }
}
